# Generated by Django 4.2 on 2023-06-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servisarg", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trabajador",
            options={},
        ),
        migrations.AlterModelManagers(
            name="trabajador",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="password",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="username",
        ),
        migrations.AddField(
            model_name="trabajador",
            name="apellido",
            field=models.CharField(default=14, max_length=130, verbose_name="Apellido"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trabajador",
            name="clave",
            field=models.CharField(
                default=14, max_length=20, verbose_name="Contraseña"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trabajador",
            name="nombre",
            field=models.CharField(default=0, max_length=130, verbose_name="Nombre"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="telefono",
            field=models.IntegerField(unique=True, verbose_name="Telefono"),
        ),
    ]
