# Generated by Django 4.2 on 2023-06-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "servisarg",
            "0002_alter_trabajador_options_alter_trabajador_managers_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensaje",
            name="contenido",
        ),
        migrations.RemoveField(
            model_name="mensaje",
            name="emisor",
        ),
        migrations.RemoveField(
            model_name="mensaje",
            name="receptor",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="ContenidoMensaje",
        ),
        migrations.DeleteModel(
            name="Mensaje",
        ),
    ]
